name: zhang2019
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.14
  - ipykernel
  - jupyterlab
  - ftfy
  - matplotlib
  - numpy
  - pandas
  - Pillow
  - pooch
  - tqdm
  - wordcloud
